const Mock = require('mockjs');
const mockUtil = require('../mockUtil');

const mockData = {
  'POST /gateway/talent-gateway-service/account-service/outside/login': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      STRING: '11eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTY1OTY0NTUsInVzZXJJZCI6InVzZXIwMDEifQ.Ao4mKjIXFDZwfjzxvpsMJsEj9Jfgui0ztgEDTFNHerw',
    })));
  },
  'GET /gateway/privilege-service/privilege/function/queryByTenantIdAndUserId': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      headUrl: null,
      orgId: 'CR0012000179',
      orgName: '华润云',
      prefix: '0755',
      userAccount: '',
      userId: null,
      userMail: '13145850002@crc.com.hk',
      userMobile: '13145850002',
      userName: '租户管理员',
      userStatus: 0,
      userType: 0,
      tenantId: 'CR0011000054',
      orgParentId: 'CR0012000177',
      orgParentName: '智慧技术部',
      roleList: [{
        roleId: null, tenantId: null, roleCode: 'ORG_ADMIN', roleName: '部门负责人', createTime: null, updateTime: null, orgId: 'CR0012000225',
      }],
      privilegeList: [
        {
          children: null,
          createTime: '2020-08-06T19:42:53',
          createdBy: '1234567890000',
          functionCode: 'workbench',
          functionEvent: 'rmSubMenu,moveMenu,leaveMenu',
          functionFullCode: null,
          functionId: 115,
          functionName: '主页',
          functionSequence: 1,
          functionType: 'MENU',
          parentId: null,
          permissionCode: 'overview1',
          resourceUrl: 'overview',
          status: 'Y',
          updateBy: '1234567890002',
          updateTime: '2020-08-20T10:28:14',
        },
        {
          children: [
            {
              children: null,
              createTime: '2020-08-06T19:42:53',
              createdBy: '1234567890000',
              functionCode: 'PSN_INFO',
              functionEvent: null,
              functionFullCode: null,
              functionId: 106,
              functionName: '个人信息',
              functionSequence: 1,
              functionType: 'PAGE',
              parentId: 103,
              permissionCode: null,
              resourceUrl: null,
              status: 'Y',
              updateBy: '1234567890000',
              updateTime: '2020-08-06T19:40:48',
            },
            {
              children: null,
              createTime: '2020-08-06T19:42:53',
              createdBy: '1234567890000',
              functionCode: 'PSN_CONF',
              functionEvent: null,
              functionFullCode: null,
              functionId: 109,
              functionName: '个人设置',
              functionSequence: 2,
              functionType: 'PAGE',
              parentId: 103,
              permissionCode: null,
              resourceUrl: null,
              status: 'Y',
              updateBy: '1234567890000',
              updateTime: '2020-08-06T19:40:48',
            },
          ],
          createTime: '2020-08-06T19:42:53',
          createdBy: '1234567890000',
          functionCode: 'PERSON',
          functionEvent: null,
          functionFullCode: null,
          functionId: 103,
          functionName: '个人中心',
          functionSequence: 2,
          functionType: 'MENU',
          parentId: null,
          permissionCode: null,
          resourceUrl: null,
          status: 'O',
          updateBy: '1234567890002',
          updateTime: '2020-08-19T20:05:37',
        },
        {
          children: null,
          createTime: '2020-08-19T16:27:57',
          createdBy: '1234567890003',
          functionCode: 'telent',
          functionEvent: 'rmSubMenu,moveMenu,leaveMenu',
          functionFullCode: null,
          functionId: 490,
          functionName: '租户管理',
          functionSequence: 11,
          functionType: 'MENU',
          parentId: null,
          permissionCode: 'organizeManage',
          resourceUrl: 'organizeManage',
          status: 'Y',
          updateBy: '1234567890003',
          updateTime: '2020-08-19T16:29:16',
        },
        {
          children: null,
          createTime: '2020-08-19T16:30:07',
          createdBy: '1234567890003',
          functionCode: 'system',
          functionEvent: 'rmSubMenu,moveMenu,leaveMenu',
          functionFullCode: null,
          functionId: 493,
          functionName: '系统管理',
          functionSequence: 12,
          functionType: 'MENU',
          parentId: null,
          permissionCode: 'tenantManage',
          resourceUrl: 'tenantManage',
          status: 'Y',
          updateBy: '1234567890003',
          updateTime: '2020-08-19T16:30:07',
        },
        {
          children: [
            {
              children: null,
              createTime: null,
              createdBy: null,
              functionCode: 'organize-menu',
              functionEvent: 'rmSubMenu,moveMenu,leaveMenu',
              functionFullCode: null,
              functionId: 175,
              functionName: '部门管理',
              functionSequence: 1,
              functionType: 'MENU',
              parentId: 166,
              permissionCode: 'organizeManage',
              resourceUrl: 'organizeManage',
              status: 'S',
              updateBy: '1234567890003',
              updateTime: '2020-08-19T16:46:02',
            },
            {
              children: null,
              createTime: null,
              createdBy: null,
              functionCode: 'organize-menu',
              functionEvent: 'rmSubMenu,moveMenu,leaveMenu',
              functionFullCode: null,
              functionId: 175,
              functionName: '部门管理',
              functionSequence: 1,
              functionType: 'MENU',
              parentId: 166,
              permissionCode: 'organizeManage',
              resourceUrl: 'organizeManage',
              status: 'S',
              updateBy: '1234567890003',
              updateTime: '2020-08-19T16:46:02',
            },
            {
              children: [{
                children: null,
                createTime: '2020-08-06T19:42:53',
                createdBy: '1234567890000',
                functionCode: 'OKR_SET',
                functionEvent: null,
                functionFullCode: null,
                functionId: 88,
                functionName: '设置OKR',
                functionSequence: 1,
                functionType: 'PAGE',
                parentId: 181,
                permissionCode: null,
                resourceUrl: null,
                status: 'Y',
                updateBy: '1234567890000',
                updateTime: '2020-08-06T19:40:48',
              }, {
                children: null,
                createTime: '2020-08-06T19:42:53',
                createdBy: '1234567890000',
                functionCode: 'OKR_PERIOD',
                functionEvent: null,
                functionFullCode: null,
                functionId: 94,
                functionName: 'OKR周期与自评',
                functionSequence: 2,
                functionType: 'PAGE',
                parentId: 181,
                permissionCode: null,
                resourceUrl: null,
                status: 'Y',
                updateBy: '1234567890000',
                updateTime: '2020-08-06T19:40:48',
              }],
              createTime: null,
              createdBy: null,
              functionCode: 'settings-menu',
              functionEvent: 'isExtend,moveMenu,leaveMenu',
              functionFullCode: null,
              functionId: 181,
              functionName: '设置管理',
              functionSequence: 3,
              functionType: 'MENU',
              parentId: 166,
              permissionCode: 'okrPermissions',
              resourceUrl: 'okrPermissions',
              status: 'S',
              updateBy: '1234567890003',
              updateTime: '2020-08-19T16:47:33',
            },
          ],
          createTime: null,
          createdBy: null,
          functionCode: 'TENANT',
          functionEvent: 'rmSubMenu,moveMenu,leaveMenu',
          functionFullCode: null,
          functionId: 166,
          functionName: '租户管理',
          functionSequence: 8,
          functionType: 'MENU',
          parentId: null,
          permissionCode: 'tenantManage',
          resourceUrl: 'tenantManage',
          status: 'S',
          updateBy: '1234567890003',
          updateTime: '2020-08-19T16:17:03',
        },
      ],
      tenantInfo: {
        applyUser: 'xx',
        createTime: '2020-08-10T10:51:03',
        createdBy: '1234567890000',
        endTime: '2021-08-10T10:50:50',
        mobilePhone: '13101010002',
        startTime: '2020-08-10T10:50:47',
        status: 'O',
        tenantBuId: 'CR0011000054',
        tenantId: 'CR0011000054',
        tenantName: '华润集团-智信部',
        updateBy: '1234567890000',
        updateTime: '2020-08-20T12:40:49',
      },
    })));
  },
  // 查询组织树
  'POST /gateway/talent-query/okr/query/orgTable': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      children: [
        {
          createTime: null,
          orgAvailable: 0,
          orgFullId: '11-88',
          orgId: '88881111',
          orgName: '智慧技术部',
          orgParentId: '8888',
          orgType: 0,
          tenantId: null,
          updateTime: null,
          children: [
            {
              createTime: '2020-08-04 16:29:54',
              orgAvailable: 0,
              orgFullId: '11-11-88',
              orgId: '888811111111',
              orgName: '工业互联网平台',
              orgParentId: '88881111',
              orgType: 0,
              tenantId: '88888888',
              updateTime: null,
            },
            {
              createTime: '2020-08-04 16:29:54',
              orgAvailable: 0,
              orgFullId: '22-11-88',
              orgId: '888811112222',
              orgName: '大数据平台',
              orgParentId: '88881111',
              orgType: 0,
              tenantId: '88888888',
              updateTime: null,
            },
            {
              createTime: '2020-08-04 16:29:54',
              orgAvailable: 0,
              orgFullId: '33-11-88',
              orgId: '888811113333',
              orgName: '人工智能平台',
              orgParentId: '88881111',
              orgType: 0,
              tenantId: '88888888',
              updateTime: null,
            },
          ],
        },
        {
          createTime: null,
          orgAvailable: 0,
          orgFullId: '22-88',
          orgId: '88882222',
          orgName: '华润云',
          orgParentId: '8888',
          orgType: 0,
          tenantId: null,
          updateTime: null,
          children: [{
            createTime: '2020-08-04 16:29:54',
            orgAvailable: 0,
            orgFullId: '11-22-88',
            orgId: '888822221111',
            orgName: '磐云',
            orgParentId: '88882222',
            orgType: 0,
            tenantId: '88888888',
            updateTime: null,
          },
          ],
        },
      ],
      createTime: null,
      orgAvailable: 0,
      orgFullId: '88',
      orgId: '8888',
      orgName: '润联科技',
      orgParentId: null,
      orgType: 0,
      tenantId: null,
      updateTime: null,
    })));
  },
};
module.exports = mockData;