export default {
  weekList: [],
  week: {},
  projectList: [],
  originalMyOkrList: [],
  myOkrPeriodList: [],
  myOkrList: [],
  originalOrgOkrList: [],
  orgOkrPeriodList: [],
  orgOkrList: [],
  cultureList: [],
  configItemCodeOKR: '',
  // weeklyType: '',
  currentWeek: {},
};