export default {
  weekList: [],
  weeklyDataList: [{}],
  setWeeklyType: {},
  weeklyTypeList: [],
  week: {},
  projectList: [],
  originalMyOkrList: [],
  myOkrPeriodList: [],
  myOkrList: [],
  originalOrgOkrList: [],
  orgOkrPeriodList: [],
  orgOkrList: [],
  cultureList: [],
  configItemCodeOKR: '',
};