const Mock = require('mockjs');
const mockUtil = require('../mockUtil');

const mockData = {
  'POST /gateway/system-service/sys/role/listRolePage': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      'content|10': [{
        'roleCode|+1': 1,
        roleName: 'US20190210_111001',
        'roleType|1': ['SYSTEM', 'CREATION'],
        'version|1': ['基础版', '旗舰版'],
        createTime: '@datetime()',
      }],
      currentPage: 1,
      pageSize: 10,
      total: 100,
    })));
  },
  'POST /gateway/system-service/sys/userRole/listRoleUser': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      'content|20': [{
        userAccount: '18867671524',
        userName: '@cname',
        userMobile: '18867671524',
        orgName: '西天旅游团',
        createTime: '@datetime()',
      }],
      currentPage: 1,
      pageSize: 10,
      total: 20,
    })));
  },
  'POST /gateway/system-service/sys/function/listTenantFuncation': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      ARRAY: [
        {
          functionId: 4,
          parentId: null,
          functionCode: 'SYSTEM',
          functionName: '系统管理',
          functionSequence: 1,
          functionFullCode: null,
          functionType: 'MENU',
          permissionCode: 'system:mng:list',
          resourceUrl: null,
          status: 'O',
          createdBy: '1234567890000',
          createTime: '2020-08-06T19:40:48',
          updateTime: '2020-08-06T19:49:54',
          updateBy: '1234567890000',
          children: [
            {
              functionId: 7,
              parentId: 4,
              functionCode: 'TENANT',
              functionName: '租户管理',
              functionSequence: 1,
              functionFullCode: null,
              functionType: 'PAGE',
              permissionCode: 'system:tenant:list',
              resourceUrl: '',
              status: 'Y',
              createdBy: '1234567890000',
              createTime: '2020-08-06T19:42:53',
              updateTime: '2020-08-06T19:40:48',
              updateBy: '1234567890000',
              children: [
                {
                  functionId: 28,
                  parentId: 7,
                  functionCode: 'CREATE',
                  functionName: '创建',
                  functionSequence: 1,
                  functionFullCode: null,
                  functionType: 'BTN',
                  permissionCode: 'system:tenant:create',
                  resourceUrl: '',
                  status: 'O',
                  createdBy: '1234567890000',
                  createTime: '2020-08-06T19:42:53',
                  updateTime: '2020-08-06T19:40:48',
                  updateBy: '1234567890000',
                  children: null,
                },
                {
                  functionId: 31,
                  parentId: 7,
                  functionCode: 'UPDATE',
                  functionName: '编辑',
                  functionSequence: 1,
                  functionFullCode: null,
                  functionType: 'BTN',
                  permissionCode: 'system:tenant:update',
                  resourceUrl: '',
                  status: 'Y',
                  createdBy: '1234567890000',
                  createTime: '2020-08-06T19:42:53',
                  updateTime: '2020-08-06T19:40:48',
                  updateBy: '1234567890000',
                  children: null,
                },
                {
                  functionId: 34,
                  parentId: 7,
                  functionCode: 'QUERY',
                  functionName: '查询',
                  functionSequence: 1,
                  functionFullCode: null,
                  functionType: 'BTN',
                  permissionCode: 'system:tenant:query',
                  resourceUrl: '',
                  status: 'Y',
                  createdBy: '1234567890000',
                  createTime: '2020-08-06T19:42:53',
                  updateTime: '2020-08-06T19:40:48',
                  updateBy: '1234567890000',
                  children: null,
                },
              ],
            },
            {
              functionId: 10,
              parentId: 4,
              functionCode: 'USER',
              functionName: '用户管理',
              functionSequence: 2,
              functionFullCode: null,
              functionType: 'PAGE',
              permissionCode: 'system:user:list',
              resourceUrl: '',
              status: 'Y',
              createdBy: '1234567890000',
              createTime: '2020-08-06T19:42:53',
              updateTime: '2020-08-06T19:40:48',
              updateBy: '1234567890000',
              children: null,
            },
            {
              functionId: 13,
              parentId: 4,
              functionCode: 'DEPARTMENT',
              functionName: '部门管理',
              functionSequence: 3,
              functionFullCode: null,
              functionType: 'PAGE',
              permissionCode: 'system:dept:list',
              resourceUrl: '',
              status: 'Y',
              createdBy: '1234567890000',
              createTime: '2020-08-06T19:42:53',
              updateTime: '2020-08-06T19:40:48',
              updateBy: '1234567890000',
              children: null,
            },
            {
              functionId: 16,
              parentId: 4,
              functionCode: 'DICTIONARY',
              functionName: '字典管理',
              functionSequence: 4,
              functionFullCode: null,
              functionType: 'PAGE',
              permissionCode: 'system:dict:list',
              resourceUrl: '',
              status: 'Y',
              createdBy: '1234567890000',
              createTime: '2020-08-06T19:42:53',
              updateTime: '2020-08-06T19:40:48',
              updateBy: '1234567890000',
              children: null,
            },
            {
              functionId: 19,
              parentId: 4,
              functionCode: 'MENU',
              functionName: '菜单管理',
              functionSequence: 5,
              functionFullCode: null,
              functionType: 'PAGE',
              permissionCode: 'system:menu:list',
              resourceUrl: '',
              status: 'Y',
              createdBy: '1234567890000',
              createTime: '2020-08-06T19:42:53',
              updateTime: '2020-08-06T19:40:48',
              updateBy: '1234567890000',
              children: null,
            },
            {
              functionId: 22,
              parentId: 4,
              functionCode: 'PERMISSION',
              functionName: '系统权限',
              functionSequence: 6,
              functionFullCode: null,
              functionType: 'MENU',
              permissionCode: 'system:perm:list',
              resourceUrl: '',
              status: 'Y',
              createdBy: '1234567890000',
              createTime: '2020-08-06T19:42:53',
              updateTime: '2020-08-06T19:40:48',
              updateBy: '1234567890000',
              children: [
                {
                  functionId: 25,
                  parentId: 22,
                  functionCode: 'USER',
                  functionName: '系统用户管理',
                  functionSequence: 1,
                  functionFullCode: null,
                  functionType: 'PAGE',
                  permissionCode: 'system:perm:user:list',
                  resourceUrl: '',
                  status: 'Y',
                  createdBy: '1234567890000',
                  createTime: '2020-08-06T19:42:53',
                  updateTime: '2020-08-06T19:40:48',
                  updateBy: '1234567890000',
                  children: null,
                },
              ],
            },
          ],
        },
      ],

      currentPage: 1,
      pageSize: 10,
      total: 10,
    })));
  },

  'POST /gateway/system-service/sys/user/listOrgUser': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      'content|10': [{
        'id|+1': 1,
        'userId|+1': 1,
        orgId: 'US20190210_111001',
        userName: '@cname',
        createTime: '@datetime()',
      }],
    })));
  },
  'POST /gateway/system-service/sys/role/getRole': (req, res) => {
    res.send(mockUtil.getSuccessData(Mock.mock({
      'ARRAY|1': [{
        currentPage: 1,
        keyWord: null,
        menuTree: [[4, 7], [4, 13]],
        pageSize: 10,
        roleCode: 'SYS_ADMIN',
        roleName: '系统管理员',
        sortOrderBy: 'ASC',
        sortPropName: null,
        tenantId: null,
      }],
    })));
  },
};
module.exports = mockData;